### ISSUE TITLE
Reload app?

### ISSUE THREAD

**Issue by littlefyr** [elmasse/elmasse-bundle#18]
Hey, 

This _might_ be more of an example to put into the demo, but if you were build a Single Page App, then you would need the ability to change the language _after_ the app is initialized. 

The trivial approach is to set a cookie or local storage and then reload the page. But if the preference is stored in the user model (because you also send server generated notifications in the preferred language, perhaps) then you will get the language _after_ everything is initialized. This is a normal usecase, I would think. 

Reloading the page once you get a different language from the user (and using cookies et. al.) is a bad approach. There should be a better solution. 

If it changes how you create your app, so be it, but that should be demonstrated at least.

**Comment by elmasse** [comment]
There is a new example using ViewModels and ViewControllers in v1.1.0 to showcase how to change language on the fly. See https://github.com/elmasse/elmasse-bundle/tree/master/examples/demo-classic-vm
