### ISSUE TITLE
examples & without using cmd

### ISSUE THREAD

**Issue by forktheweb** [elmasse/elmasse-bundle#19]
I took a look at your bundles cause I think it's what I need as far as organizing resources goes, but I'm not sure.  the clone was severely lacking examples and use cases.

I'm building a language that dynamically generates MVCS/W based on data sets from multiple sources (aws rds/aurora, dynamo, mongo, postgre, etc.) and uses those to create ExtJS code, and Swagger APIs.   Anyhow, I like the idea of bundling apps together in a way where the resources are accessible and less disorganized.   You don't state your rationale in the Readme.md  ... if you have time hit me up on hc:irc(freenode:disruptive)  or dr.hogan@objectcode.org   https://www.hipchat.com/invite/513222/8ed949451ff5a195079c84e1bd1e633b?utm_campaign=company_room_link   

Here's the project I've been barely starting, much of the code is crypto and/or written in go/php/ruby/bash and designed for docker/heroku with elastic beanstalk or EC2 AMI.

https://github.com/largesoft/skel

I'm still at odds as to whether or not to generate columns & fields from JSON and load them with the Ext.Loader, or if I should just have the server-side language create the models and corresponding stores, grids, etc. 

For instance:  right now I can generate columns in JSON or array
http://a.badasscrm.com/skel/make.columns.php?c=contacts
http://a.badasscrm.com/skel/make.columns.php?c=contacts&f=array

It has become apparent to me that it's not common to pull the fields/columns/associations/validations from JSON, but rather to write the models.  So I guess I'm leaning more towards just creating the models dynamically and linking it to an api.  But I'm gonna make my own shorthand for it using functions like this:

    function createModel(fields) {
    return Ext.define('Rex.store.reading.Skel' + Ext.id(), {
            extend: 'Ext.data.Model',
            fields: fields,    
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json',
                    totalProperty: 'tc',
                    root: 'Result'
                }
            }
        }
    });

The end result would allow the user to create sophisticated apps, because the software is designed to allow them to manage fields/columns across a broad spectrum or applications.  
https://www.lucidchart.com/documents/edit/4a9babed-a1be-46e6-8f18-aebefcbbca0e?shared=true&

I've been doing web a long time, and it's a very fun project cause of the end goal for me.  I love AWS and am devout ;)

.... So I'm not sure if this fits in with what you are doing... but yours is the closest thing I've found to a packaged solution that can be distributed for ExtJS open source with software like mine in container apps for the purpose of rapid deployment. 

Cheers!
<< sorry for the long rant... I do that.... haha >>

**Comment by largesoft** [comment]
also just fyi I am a long time tango dancer.  LOL
